id: I3F447CB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-24T18:30:13+00:00'
last_modified: '2022-06-14T08:25:57.814737+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4313
  title: གྲགས་ཆེན་བཅོ་བརྒྱད།
  author: ''
  base:
    15C3:
      image_group_id: I1KG17482
      title: ''
      total_pages: ''
      order: 1
      base_file: 15C3.txt
    E558:
      image_group_id: I1KG17483
      title: ''
      total_pages: ''
      order: 2
      base_file: E558.txt
    1B50:
      image_group_id: I1KG17484
      title: ''
      total_pages: ''
      order: 3
      base_file: 1B50.txt
    6CF6:
      image_group_id: I1KG17485
      title: ''
      total_pages: ''
      order: 4
      base_file: 6CF6.txt
    36D1:
      image_group_id: I1KG17486
      title: ''
      total_pages: ''
      order: 5
      base_file: 36D1.txt
    45C8:
      image_group_id: I1KG17487
      title: ''
      total_pages: ''
      order: 6
      base_file: 45C8.txt
    5AEE:
      image_group_id: I1KG17488
      title: ''
      total_pages: ''
      order: 7
      base_file: 5AEE.txt
    38EC:
      image_group_id: I1KG17489
      title: ''
      total_pages: ''
      order: 8
      base_file: 38EC.txt
    677C:
      image_group_id: I1KG17490
      title: ''
      total_pages: ''
      order: 9
      base_file: 677C.txt
    C54B:
      image_group_id: I1KG17491
      title: ''
      total_pages: ''
      order: 10
      base_file: C54B.txt
    FB6A:
      image_group_id: I1KG17492
      title: ''
      total_pages: ''
      order: 11
      base_file: FB6A.txt
    222C:
      image_group_id: I1KG17493
      title: ''
      total_pages: ''
      order: 12
      base_file: 222C.txt
    E94E:
      image_group_id: I1KG17494
      title: ''
      total_pages: ''
      order: 13
      base_file: E94E.txt
    '1940':
      image_group_id: I1KG17495
      title: ''
      total_pages: ''
      order: 14
      base_file: 1940.txt
    AFC1:
      image_group_id: I1KG17496
      title: ''
      total_pages: ''
      order: 15
      base_file: AFC1.txt
    '0162':
      image_group_id: I1KG17497
      title: ''
      total_pages: ''
      order: 16
      base_file: 0162.txt
    '9035':
      image_group_id: I1KG17498
      title: ''
      total_pages: ''
      order: 17
      base_file: 9035.txt
    '8564':
      image_group_id: I1KG17499
      title: ''
      total_pages: ''
      order: 18
      base_file: 8564.txt
    9C1C:
      image_group_id: I1KG17500
      title: ''
      total_pages: ''
      order: 19
      base_file: 9C1C.txt
    9D29:
      image_group_id: I1KG17501
      title: ''
      total_pages: ''
      order: 20
      base_file: 9D29.txt
    E4D8:
      image_group_id: I1KG17502
      title: ''
      total_pages: ''
      order: 21
      base_file: E4D8.txt
    D41B:
      image_group_id: I1KG17503
      title: ''
      total_pages: ''
      order: 22
      base_file: D41B.txt
    D48F:
      image_group_id: I1KG17504
      title: ''
      total_pages: ''
      order: 23
      base_file: D48F.txt
    DC24:
      image_group_id: I1KG17505
      title: ''
      total_pages: ''
      order: 24
      base_file: DC24.txt
    E7EB:
      image_group_id: I1KG17506
      title: ''
      total_pages: ''
      order: 25
      base_file: E7EB.txt
    BB38:
      image_group_id: I1KG17507
      title: ''
      total_pages: ''
      order: 26
      base_file: BB38.txt
    C4F2:
      image_group_id: I1KG17508
      title: ''
      total_pages: ''
      order: 27
      base_file: C4F2.txt
    FEE2:
      image_group_id: I1KG17509
      title: ''
      total_pages: ''
      order: 28
      base_file: FEE2.txt
    3DE4:
      image_group_id: I1KG17510
      title: ''
      total_pages: ''
      order: 29
      base_file: 3DE4.txt
    BBAD:
      image_group_id: I1KG17511
      title: ''
      total_pages: ''
      order: 30
      base_file: BBAD.txt
    3C00:
      image_group_id: I1KG17512
      title: ''
      total_pages: ''
      order: 31
      base_file: 3C00.txt
    933C:
      image_group_id: I1KG17513
      title: ''
      total_pages: ''
      order: 32
      base_file: 933C.txt
    618D:
      image_group_id: I1KG17514
      title: ''
      total_pages: ''
      order: 33
      base_file: 618D.txt
    '5486':
      image_group_id: I1KG17515
      title: ''
      total_pages: ''
      order: 34
      base_file: 5486.txt
    777A:
      image_group_id: I1KG17516
      title: ''
      total_pages: ''
      order: 35
      base_file: 777A.txt
    22A5:
      image_group_id: I1KG17517
      title: ''
      total_pages: ''
      order: 36
      base_file: 22A5.txt
    BD9C:
      image_group_id: I1KG17518
      title: ''
      total_pages: ''
      order: 37
      base_file: BD9C.txt
    441E:
      image_group_id: I1KG17519
      title: ''
      total_pages: ''
      order: 38
      base_file: 441E.txt
    88FE:
      image_group_id: I1KG17520
      title: ''
      total_pages: ''
      order: 39
      base_file: 88FE.txt
    6AB2:
      image_group_id: I1KG17521
      title: ''
      total_pages: ''
      order: 40
      base_file: 6AB2.txt
    10D5:
      image_group_id: I1KG17522
      title: ''
      total_pages: ''
      order: 41
      base_file: 10D5.txt
    '1999':
      image_group_id: I1KG17523
      title: ''
      total_pages: ''
      order: 42
      base_file: 1999.txt
    58D4:
      image_group_id: I1KG17524
      title: ''
      total_pages: ''
      order: 43
      base_file: 58D4.txt
    '8992':
      image_group_id: I1KG17525
      title: ''
      total_pages: ''
      order: 44
      base_file: 8992.txt
    2EAE:
      image_group_id: I1KG17526
      title: ''
      total_pages: ''
      order: 45
      base_file: 2EAE.txt
    4AB6:
      image_group_id: I1KG17527
      title: ''
      total_pages: ''
      order: 46
      base_file: 4AB6.txt
    '9359':
      image_group_id: I1KG17528
      title: ''
      total_pages: ''
      order: 47
      base_file: 9359.txt
    F0E7:
      image_group_id: I1KG17529
      title: ''
      total_pages: ''
      order: 48
      base_file: F0E7.txt
    '7726':
      image_group_id: I1KG17530
      title: ''
      total_pages: ''
      order: 49
      base_file: 7726.txt
    6BD8:
      image_group_id: I1KG17531
      title: ''
      total_pages: ''
      order: 50
      base_file: 6BD8.txt
    '3702':
      image_group_id: I1KG17532
      title: ''
      total_pages: ''
      order: 51
      base_file: 3702.txt
    14F8:
      image_group_id: I1KG17533
      title: ''
      total_pages: ''
      order: 52
      base_file: 14F8.txt
    42C4:
      image_group_id: I1KG17534
      title: ''
      total_pages: ''
      order: 53
      base_file: 42C4.txt
    '2036':
      image_group_id: I1KG17535
      title: ''
      total_pages: ''
      order: 54
      base_file: 2036.txt
    744E:
      image_group_id: I1KG17536
      title: ''
      total_pages: ''
      order: 55
      base_file: 744E.txt
    EA9D:
      image_group_id: I1KG17537
      title: ''
      total_pages: ''
      order: 56
      base_file: EA9D.txt
    DD25:
      image_group_id: I1KG17538
      title: ''
      total_pages: ''
      order: 57
      base_file: DD25.txt
    DF68:
      image_group_id: I1KG17539
      title: ''
      total_pages: ''
      order: 58
      base_file: DF68.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
